#!/bin/bash

PORTDIR=/usr/portage
SABAYON_LAYMAN=/var/lib/layman/sabayon

# Fix temporary issue on compile dev-libs/klibc
# See: https://bugs.gentoo.org/621848

klibc_version="2.0.4-r2"
echo "Fix compilation of dev-libs/klibc..."

sed -i -e 's/KV_SUB="4"/KV_SUB="14"/g' \
  ${PORTDIR}/dev-libs/klibc/klibc-${klibc_version}.ebuild
ebuild ${PORTDIR}/dev-libs/klibc/klibc-${klibc_version}.ebuild digest

# Fix compilation of v86d when there aren't kernel under /usr.
# In this case I use linux-headers package.
v86d_version="0.1.10-r1"
sed -i -e 's:#append-cflags.*:append-cflags "-I/usr/include":g' \
  ${SABAYON_LAYMAN}/sys-apps/v86d/v86d-${v86d_version}.ebuild
ebuild ${SABAYON_LAYMAN}/sys-apps/v86d/v86d-${v86d_version}.ebuild digest

echo "End pre-script"

exit 0

# vim: ts=2 sw=2 expandtab filetype=sh
