---

# Author: Geaaru, geaaru@gmail.com
# Description: Role for create lxd image from docker

- name: "{{ current_build }}: Clean staging dir rootfs"
  become: true
  become_user: root
  file:
    path: "{{ staging_dir }}/rootfs"
    state: absent
  ignore_errors: yes

- name: "{{ current_build }}: Create LXD image"
  vars:
    sab_lxd_imagebuilder_opts: "{{ lxd_imagebuilder_opts | default('') }}"
    sab_lxd_imagebuilder: "{{ lxd_imagebuilder | default('sabayon-lxd-imagebuilder') }}"
  environment:
    LXD_TARGET: "{{ lxd_target_server | default('') }}"
    OS: "{{ lxd_os_image | default('sabayon') }}"
    DISTRO: "{{ lxd_distro_image | default('Sabayon') }}"
    RELEASE: "{{ lxd_release_image | default('daily') }}"
    UNPRIVILEGED: "{{ lxd_unprivileged_image | default('') }}"
    UNPRIVILEGED_FUNCTIONS: "{{ lxd_unpriv_funcs | default('') }}"
    IMAGE_ALIAS: "{{ lxd_image_alias | default('') }}"
    IMAGE_DESCR: "{{ lxd_image_descr | default('') }}"
    PULL_SKIP: "{{ lxd_skip_pull }}"
  become: true
  become_user: root
  command: >
    {{ sab_lxd_imagebuilder }}
    --stagingdir {{ staging_dir}}
    --image {{ docker_image_name }}
    --import
    {{ sab_lxd_imagebuilder_opts }}
  register: sabayon_lxd_imagebuilder

- name: "{{ current_build }}: Get image Id"
  set_fact:
    image_id: "{{ ( sabayon_lxd_imagebuilder.stdout | regex_search('fingerprint: .*') ).split(' ')[1] }}"

