---
- hosts:
    - all
  tasks:

    - name: Build AMD64 image
      tags:
        - amd64
      vars:
        current_arch: 'amd64'
        for_amd64: True
        for_arm: False
        sabayon_arch: 'amd64'
      block:

        - name: Check QEMU
          tags:
            - amd64_gentoo_stage3
            - amd64_sabayon_stage3
            - amd64_sabayon_base
            - amd64_sabayon_spinbase
            - amd64_sabayon_builder
            - amd64_sabayon_stage3_reload
            - amd64_sabayon_create_repo
            - amd64_sabayon_base_reload
            - amd64_sabayon_check_overlay
          include_role:
            name: commons
            tasks_from: check_qemu

        - name: Build Gentoo Stage3
          vars:
            docker_build_opts: ''
          tags:
            - amd64_gentoo_stage3
          include_role:
            name: build
            tasks_from: gentoo_stage3

        - name: Build Sabayon Stage3
          tags:
            - amd64_sabayon_stage3
          include_role:
            name: build
            tasks_from: sabayon_stage3

        - name: Build Sabayon Stage3 Reload
          tags:
            - amd64_sabayon_stage3_reload
          include_role:
            name: build
            tasks_from: sabayon_stage3_reload

        - name: Build Sabayon Create Repo
          tags:
            - amd64_sabayon_create_repo
          include_role:
            name: build
            tasks_from: sabayon_create_repo

        - name: Build Sabayon Base
          tags:
            - amd64_sabayon_base
          include_role:
            name: build
            tasks_from: sabayon_base

        - name: Build Sabayon Base Reload
          tags:
            - amd64_sabayon_base_reload
          include_role:
            name: build
            tasks_from: sabayon_base_reload

        - name: Build Sabayon Spinbase
          tags:
            - amd64_sabayon_spinbase
          include_role:
            name: build
            tasks_from: sabayon_spinbase

        - name: Build Sabayon Builder
          tags:
            - amd64_sabayon_builder
          include_role:
            name: build
            tasks_from: sabayon_builder

        - name: Build Sabayon Check Overlay
          tags:
            - amd64_sabayon_check_overlay
          include_role:
            name: build
            tasks_from: sabayon_check_overlay

    - name: Build ARM-7A image
      tags:
        - arm7
      vars:
        current_arch: 'armv7a_hardfp'
        for_amd64: False
        for_arm: True
        sabayon_arch: 'arm'
      block:

        - name: Check QEMU
          tags:
            - arm7_gentoo_stage3
            - arm7_sabayon_stage3
            - arm7_sabayon_base
            - arm7_sabayon_spinbase
            - arm7_sabayon_builder
          include_role:
            name: commons
            tasks_from: check_qemu

        - name: Build Gentoo Stage3
          vars:
            docker_build_opts: '--build-arg GENTOO_PROFILE_NAME=/armv7a/systemd'
          tags:
            - arm7_gentoo_stage3
          include_role:
            name: build
            tasks_from: arm7_gentoo_stage3

        - name: Block for arm7a
          vars:
            docker_build_opts: >
              --build-arg GENTOO_PROFILE_NAME=/armv7a/systemd
              --build-arg TARGET_ARCH={{ current_arch }}
          block:
            - name: Build Sabayon Stage3
              tags:
                - arm7_sabayon_stage3
              include_role:
                name: build
                tasks_from: arm7_sabayon_stage3

            - name: Build Sabayon Base
              tags:
                - arm7_sabayon_base
              include_role:
                name: build
                tasks_from: arm7_sabayon_base

#        - name: Build Sabayon Spinbase
#          include_role:
#            name: build
#            tasks_from: sabayon_spinbase

#        - name: Build Sabayon Builder
#          include_role:
#            name: build
#            tasks_from: sabayon_builder

