---
- hosts:
    - all
  tasks:
    - name: Build Gentoo Stage3
      include_role:
        name: build
        tasks_from: gentoo_stage3

    - name: Build Sabayon Stage3
      include_role:
        name: build
        tasks_from: sabayon_stage3

    - name: Build Sabayon Base
      include_role:
        name: build
        tasks_from: sabayon_base

    - name: Build Sabayon Spinbase
      include_role:
        name: build
        tasks_from: sabayon_spinbase

    - name: Build Sabayon Builder
      include_role:
        name: build
        tasks_from: sabayon_builder
